DROP TABLE IF EXISTS NURSE_ASSIGNED_TO_PATIENT;
DROP TABLE IF EXISTS TAKING;
DROP TABLE IF EXISTS DOCTOR_ATTEND_PATIENT;
DROP TABLE IF EXISTS MEDICINE;
DROP TABLE IF EXISTS NURSES;
DROP TABLE IF EXISTS SPECIALITY;
DROP TABLE IF EXISTS DOCTORS;
DROP TABLE IF EXISTS PATIENTS;

CREATE TABLE PATIENTS(
Patient_id INT(10) NOT NULL,
First_name VARCHAR(30) NOT NULL,
Last_name VARCHAR(30) NOT NULL,
Diagnosis LONGTEXT,
Phone_number VARCHAR(15),
Treatment VARCHAR(50),
PRIMARY KEY(Patient_id)
);

CREATE TABLE DOCTORS(
Doc_id INT(10) NOT NULL,
First_name VARCHAR(30) NOT NULL,
Last_name VARCHAR(30) NOT NULL,
PRIMARY KEY(Doc_id)
);

CREATE TABLE SPECIALITY(
D_id INT(10) NOT NULL,
Speciality VARCHAR(30) NOT NULL,
PRIMARY KEY(D_id,Speciality),
FOREIGN KEY(D_id) REFERENCES DOCTORS(Doc_id) 
);

CREATE TABLE NURSES(
Nurse_id INT(10) NOT NULL,
First_name VARCHAR(30) NOT NULL,
Last_name VARCHAR(30) NOT NULL,
PRIMARY KEY(Nurse_id)
);

CREATE TABLE MEDICINE(
Medicine_id INT(20) NOT NULL,
Name VARCHAR(50) NOT NULL,
Is_prescription Boolean,
PRIMARY KEY(Medicine_id)
);

CREATE TABLE DOCTOR_ATTEND_PATIENT(
D_id INT(10) NOT NULL,
P_id INT(10) NOT NULL,
Appointment_time DATETIME,
PRIMARY KEY(D_id,P_id),
FOREIGN KEY(D_id) REFERENCES DOCTORS(Doc_id),
FOREIGN KEY(P_id) REFERENCES PATIENTS(Patient_id)
);

CREATE TABLE TAKING(
P_id INT(10),
M_id INT(20),
Dose VARCHAR(30),
PRIMARY KEY(P_id,M_id),
FOREIGN KEY(P_id) REFERENCES PATIENTS(Patient_id),
FOREIGN KEY(M_id) REFERENCES MEDICINE(Medicine_id)
);

CREATE TABLE NURSE_ASSIGNED_TO_PATIENT(
N_id INT(10),
P_id INT(20),
PRIMARY KEY(N_id,P_id),
FOREIGN KEY(N_id) REFERENCES NURSES(Nurse_id),
FOREIGN KEY(P_id) REFERENCES PATIENTS(Patient_id)
);