LOAD DATA LOCAL INFILE '/home/zhong7/TaskB/DOCTORS.dat'
INTO TABLE DOCTORS
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '/home/zhong7/TaskB/NURSES.dat'
INTO TABLE NURSES
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '/home/zhong7/TaskB/PATIENTS.dat'
INTO TABLE PATIENTS
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '/home/zhong7/TaskB/SPECIALITY.dat'
INTO TABLE SPECIALITY
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '/home/zhong7/TaskB/MEDICINE.dat'
INTO TABLE MEDICINE
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '/home/zhong7/TaskB/DOCTOR_ATTEND_PATIENT.dat'
INTO TABLE DOCTOR_ATTEND_PATIENT
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '/home/zhong7/TaskB/TAKING.dat'
INTO TABLE TAKING
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '/home/zhong7/TaskB/NURSE_ASSIGNED_TO_PATIENT.dat'
INTO TABLE NURSE_ASSIGNED_TO_PATIENT
FIELDS TERMINATED BY ',';